### ISSUE TITLE
Move mark1 module to PHAL Plugin

### ISSUE THREAD

**Issue by NeonDaniel** [OpenVoiceOS/ovos-utils#123]
Port Mark1 API methods to a standalone PHAL plugin(s) and deprecate module in ovos-utils

_Originally posted by @JarbasAl in https://github.com/OpenVoiceOS/ovos-utils/pull/119#discussion_r1163307741_

**Comment by JarbasAl** [comment]
https://github.com/OpenVoiceOS/ovos-mark1-utils
