### ISSUE TITLE
Is there an option to disable the log file creation

### ISSUE THREAD

**Issue by goldyfruit** [OpenVoiceOS/ovos-utils#124]
All services creates their log file into `~/.local/state/`, which is helpful when debugging but when running inside a container `docker logs` already provides the logs.

This could lead to a container filling it's filesystem. Does OVOS has an option the possibility to disable this log creation?

**Comment by JarbasAl** [comment]
yes, set the logs path in config to `stdout`

**Comment by goldyfruit** [comment]
I'm not able to find the exact option name in `mycroft.conf`, is it juste `log_path` in the main section?

**Comment by goldyfruit** [comment]
> > I'm not able to find the exact option name in `mycroft.conf`, is it juste `log_path` in the main section?
> 
> logs.path https://github.com/OpenVoiceOS/ovos-utils/blob/dev/ovos_utils/log.py#L59

I'm confused, is it `"log_path": "stdout", `"log": {"path": "stdout"}` or `"logs": {"path": "stdout"}` ?

**Comment by goldyfruit** [comment]
`"logs": {"path": "stdout"}` it is and fixed the `stdout` with https://github.com/OpenVoiceOS/ovos-utils/pull/125
