### ISSUE TITLE
OVOS-Cookbook link goes nowhere useful

### ISSUE THREAD

**Issue by Stormfollower** [OpenVoiceOS/ovos-utils#150]
The Cookbook link goes nowhere.  It's circular and not very helpful.

**Comment by JarbasAl** [comment]
the readme has not been updated in a long time, ovos-utils started as an helper lib to create mycroft-core skills and the cookbook were the docs from back then, A LOT has changed since then and any relevant docs from there have been ported to https://openvoiceos.github.io/ovos-technical-manual
