### ISSUE TITLE
Improve test coverage

### ISSUE THREAD

**Issue by ChanceNCounter** [OpenVoiceOS/ovos-utils#2]
At the moment, as evidenced by #1, `ovos_utils` is 8% covered. That ain't great.

**Comment by NeonDaniel** [comment]
Consider at least stubbing out test classes for all remaining modules. Moving forward, added methods should always add something to tests, even if not complete at least basic tests and `#TODO`s will help keep things working

**Comment by JarbasAl** [comment]
closing this one for now https://app.codecov.io/github/OpenVoiceOS/ovos-utils

coverage is almost at 50%, a far cry from the original 8% when this issue was opened
