### ISSUE TITLE
setup.py - This should be updated to an absolute path for automations

### ISSUE THREAD

**Issue by JarbasAl** [OpenVoiceOS/ovos-utils#240]
This should be updated to an absolute path for automations, see https://github.com/OpenVoiceOS/ovos-bus-client/pull/95

_Originally posted by @NeonDaniel in https://github.com/OpenVoiceOS/ovos-utils/pull/237#discussion_r1593226864_

**Comment by mikejgray** [comment]
Looks like this was addressed already?
