### ISSUE TITLE
ntp service errors

### ISSUE THREAD

**Issue by NeonDaniel** [OpenVoiceOS/ovos-utils#59]
ntp service does not exist under Ubuntu 22.04, so this call logs exceptions. From what I can tell, the equivalent service in ubuntu 22.04 handles ntp sync on internet connection automatically. This output should probably be captured and logged in an exception.

https://github.com/OpenVoiceOS/ovos_utils/blob/4ff31021d9c52860cd71a7cdbde516cd233ee4c2/ovos_utils/system.py#L54
From the logs:
```
Failed to stop ntp.service: Interactive authentication required.
See system logs and 'systemctl status ntp.service' for details.
/bin/sh: 1: ntpd: not found
Failed to start ntp.service: Interactive authentication required.
See system logs and 'systemctl status ntp.service' for details.
```

**Comment by builderjer** [comment]
can be fixed with [this PR](https://github.com/OpenVoiceOS/ovos-utils/pull/200) I think

**Comment by builderjer** [comment]
This is fixed as of these commits

https://github.com/OpenVoiceOS/ovos-PHAL-plugin-system/commit/165930ad170252420a311689a94be1e70e44764c

https://github.com/OpenVoiceOS/ovos-utils/commit/59a7b4a9287c3366ba329fdd9aacd73cf7e88e45

https://github.com/OpenVoiceOS/ovos-plugin-manager/commit/8619ac60ac6ef703bc1c84716a4229798e66a6fa

@NeonDaniel please verify
